server:
  port: 3000

spring:
  # 데이터베이스 설정
  datasource:
    driver-class-name:  oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: PROJECT
    password: _aA123456

# JPA 설정
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create

  #라이브 리로드 설정
  devtools:
    livereload:
      enabled: true

  # 타임리프 설정
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  # 정적 자원 설정(css,js 이미지)
  web:
    resources:
      static-locations: file:src/main/resources/static/

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 60MB

  # 파일 경로 설정
  file:
    url: /upload/
    path: c:/uploads/

  # 로거 설정
  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace