#공통 설정파일
server:
  port: 3000

spring:
  # 프로필 설정
  #PROFILES:
  # active:dev

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 60MB

  # 정적 자원 설정(css,js,이미지)
    web:
      resources:
        staticLocations: file:src/main/resources/static/

  # 데이터베이스 설정
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: SPRING6
    password: _aA123456

  # 라이브 리로드 설정
  devtools:
    livereload:
      enabled: true

  # 타임리프 설정
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  #파일 설정
  file:
    url: /upload
    path: /cup/

  # 로거 설정
  logging:
    level:
      org:
        springFramework:
          jdbc: trace